I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 30, in script call
    call p1_a1 from _call_p1_a1
  File "game/p1_a1.rpy", line 7, in script
    $ _wait_for_voice_end()
  File "game/p1_a1.rpy", line 7, in <module>
    $ _wait_for_voice_end()
NameError: name '_wait_for_voice_end' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 30, in script call
    call p1_a1 from _call_p1_a1
  File "game/p1_a1.rpy", line 7, in script
    $ _wait_for_voice_end()
  File "C:\Users\Santiago Diaz\Desktop\Usco\renpy-8.2.1-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Santiago Diaz\Desktop\Usco\renpy-8.2.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/p1_a1.rpy", line 7, in <module>
    $ _wait_for_voice_end()
NameError: name '_wait_for_voice_end' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.2.1.24030407
 
Wed Apr 10 21:57:12 2024
